### ISSUE TITLE
create a style guide - server

### ISSUE THREAD

**Issue by yishain11** [Makes-Innovation-Hub/bit-mentor-server#4]
DOD:
- [x] read about coding style guide and clean code
- [x] read about python specificly: https://peps.python.org/pep-0008/
- [x] decide with the team on the main rules you think are needed
- [x] create a style guide with markdown that shows these rules + examples
(later we will add linter to enfource them)

**Comment by AdamKaabyia** [comment]
var_name - variables and func names
VarName - classes+models
GLOBAL_VA - consts+global+keys
